namespace RazorPress
{
    /// <summary>
    /// Serves as a model for <see cref="RazorPress.Template"/>.
    /// </summary>
    public class Model
    {
        private readonly Page page;

        /// <summary>
        /// Initializes a new instance of the <see cref="Model"/> class.
        /// </summary>
        public Model(Page page)
        {
            this.page = page;
        }

        /// <summary>
        /// Gets a <see cref="Page"/> object that represents the web page generated by the current <see cref="Template"/>.
        /// </summary>
        public Page Page 
        { 
            get { return this.page; } 
        }
    }
}
