namespace RazorPress
{
    /// <summary>
    /// Serves as a model for <see cref="RazorPress.Template"/>.
    /// </summary>
    public class Model
    {
        private readonly Page page = new Page();

        /// <summary>
        /// Gets a <see cref="Page"/> object that represents the web page generated by the current <see cref="Template"/>.
        /// </summary>
        public Page Page 
        { 
            get { return this.page; } 
        }
    }
}
