using RazorEngine.Templating;

namespace RazorPress.Generator
{
    /// <summary>
    /// Serves as a base class for templates generated by RazorPress.
    /// </summary>
    public class RazorTemplate : TemplateBase<RazorTemplateModel>
    {
        /// <summary>
        /// Gets the <see cref="Page"/> object representing the web page generated by this <see cref="RazorTemplate"/>.
        /// </summary>
        public Page Page 
        {
            get { return this.Model.Page; }
        }
    }
}
